name: Deploy web

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Build main branch
        run: |
          npm ci
          npm run build --if-present -- --base=/atip/
          mv dist deployme

      - name: Build all other branches
        run: |
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            if [ "$branch" != "main" ] && [ "$branch" != "gh-pages" ]; then
              echo "Building $branch"
              git checkout $branch
              if npm ci && npm run build --if-present -- --base=/atip/$branch; then
                mv dist deployme/$branch
              else
                echo "Building $branch broke; skipping"
              fi

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployme/
