name: Deploy web

on:
  push:
    branches: [main, draw_v3]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present -- --base=/atip/

      - name: Checkout experimental branch
        uses: actions/checkout@v2
        with:
          ref: draw_v3
          path: draw_v3
          clean: false

      - name: Build experimental version of web app
        run: |
          cd draw_v3
          npm ci
          npm run build --if-present -- --base=/atip/draw_v3/
          mv dist ../dist/draw_v3

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
